### ISSUE TITLE
Why are version 1 and version 2 so different?

### ISSUE THREAD

**Issue by exceting** [openmessaging/openmessaging-java#69]
I download the code, It's `master` branch, and the `pom.xml`'s version is `1.0.0-beta-SNAPSHOT`, then I checkout to branch `2.0.1-pubsub`, I see the code is so different, even package!
So, is the branch `2.0.1-pubsub` is `RELEASED`? Will the same big changes follow?

**Comment by duhenglucky** [comment]
@exceting thanks for your attention, the _master_ branch aims to provide Queue model interface and the _topic_model_ branch aim to resolve the Topic(Pubsub) issues.

These two branches are for different messaging models, because we find it difficult to unify two completely different models. If you want to unify, one problem is that the interface you need to provide is the least common multiple of the two branches. Therefore, the community temporarily incubates a new topic model in the _topic_model_ branch. After reaching production availability in the future, it may become an independent repo in GitHub. Welcome to participate and give more suggestions.

**Comment by vongosling** [comment]
2.x.y version will be the final master in the latest release.
